/*
 * Copyright (c) FishPlusPlus.
 *
 * PacketSender — send any packet from chat via:
 *   !send-packet {"name":"ClientPlaceBlock","placedBlockId":5,"quickReplace":true}
 *
 * Requires packet_descriptors.json next to HytaleClient.exe (generated by
 * generate_packet_descriptors.py).
 */
#pragma once
#include "Features/Feature.h"

class PacketSender : public Feature {
public:
    PacketSender() : Feature("PacketSender") {};

    bool CanExecute() override;
    void Initialize() override;

    // Called from OnChat with the raw JSON string (everything after "!send-packet ")
    static bool TrySend(const std::string& json);
    static bool TryReceive(const std::string& json);
};
