// AUTO-GENERATED by generate_packet_table.py — DO NOT EDIT MANUALLY
#pragma once
#include <cstddef>
#include <cstdint>
#include "sdk/Packets/PacketRegistry.h"

namespace PacketTable {

enum class FType : uint8_t {
    Int8, Int16, Int32, Int64, Float32, Float64, Bool,
    Ptr  // pointer to a managed heap object; ptr_type gives its struct name
};

struct FieldDesc {
    const char* name;
    size_t      offset;
    FType       type;
    const char* ptr_type;  // non-null only for FType::Ptr
};

// ── C2S packet table ─────────────────────────────────────────────────
struct PacketDef {
    const char* name;
    PacketIndex index;
    FieldDesc   fields[128];
    int         field_count;
};

inline const PacketDef PKT_TABLE[] = {
    { "MountMovement", MountMovement_C2S, {
        { "absolute_position", 0x08, FType::Ptr, "Position" },
        { "body_orientation", 0x10, FType::Ptr, "Direction" },
        { "movement_states", 0x18, FType::Ptr, "MovementStates" },
    }, 3 },
    { "ApplyKnockback", ApplyKnockback_S2C, {
        { "hit_position", 0x08, FType::Ptr, "Position" },
        { "x", 0x10, FType::Float32, nullptr },
        { "y", 0x14, FType::Float32, nullptr },
        { "z", 0x18, FType::Float32, nullptr },
        { "change_type", 0x1C, FType::Int8, nullptr },
    }, 5 },
    { "PlayAnimation", PlayAnimation_S2C, {
        { "item_animations_id", 0x08, FType::Ptr, "String" },
        { "animation_id", 0x10, FType::Ptr, "String" },
        { "entity_id", 0x18, FType::Int32, nullptr },
        { "slot", 0x1C, FType::Int8, nullptr },
    }, 4 },
    { "SetEntitySeed", SetEntitySeed_S2C, {
        { "entity_seed", 0x08, FType::Int32, nullptr },
    }, 1 },
    { "EntityUpdates", EntityUpdates_S2C, {
        { "removed", 0x08, FType::Ptr, "Array<int>" },
    }, 1 },
    { "SpawnModelParticles", SpawnModelParticles_S2C, {
        { "entity_id", 0x08, FType::Int32, nullptr },
    }, 1 },
    { "PlayEmote", PlayEmote_C2S, {
        { "emote_id", 0x08, FType::Ptr, "String" },
    }, 1 },
    { "ChangeVelocity", ChangeVelocity_S2C, {
        { "config", 0x08, FType::Ptr, "VelocityConfig" },
        { "x", 0x10, FType::Float32, nullptr },
        { "y", 0x14, FType::Float32, nullptr },
        { "z", 0x18, FType::Float32, nullptr },
        { "change_type", 0x1C, FType::Int8, nullptr },
    }, 5 },
    { "Pong", Pong_C2S, {
        { "time", 0x08, FType::Ptr, "InstantData" },
        { "id", 0x10, FType::Int32, nullptr },
        { "packet_queue_size", 0x14, FType::Int16, nullptr },
        { "type", 0x16, FType::Int8, nullptr },
    }, 4 },
    { "Ping", Ping_S2C, {
        { "time", 0x08, FType::Ptr, "InstantData" },
        { "id", 0x10, FType::Int32, nullptr },
        { "last_ping_value_raw", 0x14, FType::Int32, nullptr },
        { "last_ping_value_direct", 0x18, FType::Int32, nullptr },
        { "last_ping_value_tick", 0x1C, FType::Int32, nullptr },
    }, 5 },
    { "ServerDisconnect", ServerDisconnect_S2C, {
        { "reason", 0x08, FType::Ptr, "FormattedMessage" },
        { "type", 0x10, FType::Int8, nullptr },
    }, 2 },
    { "ClientDisconnect", ClientDisconnect_C2S, {
        { "reason", 0x08, FType::Int8, nullptr },
        { "type", 0x09, FType::Int8, nullptr },
    }, 2 },
    { "CancelInteractionChain", CancelInteractionChain_S2C, {
        { "forked_id", 0x08, FType::Ptr, "ForkedChainId" },
        { "chain_id", 0x10, FType::Int32, nullptr },
    }, 2 },
    { "PlayInteractionFor", PlayInteractionFor_S2C, {
        { "forked_id", 0x08, FType::Ptr, "ForkedChainId" },
        { "interacted_item_id", 0x10, FType::Ptr, "String" },
        { "entity_id", 0x18, FType::Int32, nullptr },
        { "chain_id", 0x1C, FType::Int32, nullptr },
        { "operation_index", 0x20, FType::Int32, nullptr },
        { "interaction_id", 0x24, FType::Int32, nullptr },
        { "interaction_type", 0x28, FType::Int8, nullptr },
        { "cancel", 0x29, FType::Bool, nullptr },
    }, 8 },
    { "MountNPC", MountNPC_S2C, {
        { "anchor_x", 0x08, FType::Float32, nullptr },
        { "anchor_y", 0x0C, FType::Float32, nullptr },
        { "anchor_z", 0x10, FType::Float32, nullptr },
        { "entity_id", 0x14, FType::Int32, nullptr },
    }, 4 },
    { "DismountNPC", DismountNPC_BI, {
    }, 0 },
    { "SyncInteractionChains", SyncInteractionChains_BI, {
    }, 0 },
    { "AssetPart", AssetPart_S2C, {
        { "part", 0x08, FType::Ptr, "Array<Byte>" },
    }, 1 },
    { "WorldLoadProgress", WorldLoadProgress_S2C, {
        { "status", 0x08, FType::Ptr, "FormattedMessage" },
        { "percent_complete", 0x10, FType::Int32, nullptr },
        { "percent_complete_subitem", 0x14, FType::Int32, nullptr },
    }, 3 },
    { "RequestAssets", RequestAssets_C2S, {
    }, 0 },
    { "WorldSettings", WorldSettings_S2C, {
        { "world_height", 0x08, FType::Int32, nullptr },
    }, 1 },
    { "WorldLoadFinished", WorldLoadFinished_S2C, {
    }, 0 },
    { "ViewRadius", ViewRadius_BI, {
        { "value", 0x08, FType::Int32, nullptr },
    }, 1 },
    { "PlayerOptions", PlayerOptions_C2S, {
        { "skin", 0x08, FType::Ptr, "PlayerSkin" },
    }, 1 },
    { "UpdateFeatures", UpdateFeatures_S2C, {
    }, 0 },
    { "SetTimeDilation", SetTimeDilation_S2C, {
        { "time_dilation", 0x08, FType::Float32, nullptr },
    }, 1 },
    { "AssetFinalize", AssetFinalize_S2C, {
    }, 0 },
    { "AssetInitialize", AssetInitialize_S2C, {
        { "asset", 0x08, FType::Ptr, "Asset" },
        { "size", 0x10, FType::Int32, nullptr },
    }, 2 },
    { "RequestCommonAssetsRebuild", RequestCommonAssetsRebuild_S2C, {
    }, 0 },
    { "ServerTags", ServerTags_S2C, {
    }, 0 },
    { "SetUpdateRate", SetUpdateRate_S2C, {
        { "updates_per_second", 0x08, FType::Int32, nullptr },
    }, 1 },
    { "RemoveAssets", RemoveAssets_S2C, {
    }, 0 },
    { "UpdateItemPlayerAnimations", UpdateItemPlayerAnimations_S2C, {
        { "type", 0x08, FType::Int8, nullptr },
    }, 1 },
    { "UpdateSoundEvents", UpdateSoundEvents_S2C, {
        { "max_id", 0x08, FType::Int32, nullptr },
        { "type", 0x0C, FType::Int8, nullptr },
    }, 2 },
    { "UpdateParticleSystems", UpdateParticleSystems_S2C, {
        { "type", 0x08, FType::Int8, nullptr },
    }, 1 },
    { "UpdateItemCategories", UpdateItemCategories_S2C, {
        { "type", 0x08, FType::Int8, nullptr },
    }, 1 },
    { "UpdateEmotes", UpdateEmotes_S2C, {
        { "max_id", 0x08, FType::Int32, nullptr },
        { "type", 0x0C, FType::Int8, nullptr },
    }, 2 },
    { "UpdateEntityUIComponents", UpdateEntityUIComponents_S2C, {
        { "max_id", 0x08, FType::Int32, nullptr },
        { "type", 0x0C, FType::Int8, nullptr },
    }, 2 },
    { "UpdateReverbEffects", UpdateReverbEffects_S2C, {
        { "max_id", 0x08, FType::Int32, nullptr },
        { "type", 0x0C, FType::Int8, nullptr },
    }, 2 },
    { "UpdateTranslations", UpdateTranslations_S2C, {
        { "type", 0x08, FType::Int8, nullptr },
    }, 1 },
    { "UpdateRootInteractions", UpdateRootInteractions_S2C, {
        { "max_id", 0x08, FType::Int32, nullptr },
        { "type", 0x0C, FType::Int8, nullptr },
    }, 2 },
    { "UpdateViewBobbing", UpdateViewBobbing_S2C, {
        { "type", 0x08, FType::Int8, nullptr },
    }, 1 },
    { "UpdateAmbienceFX", UpdateAmbienceFX_S2C, {
        { "max_id", 0x08, FType::Int32, nullptr },
        { "type", 0x0C, FType::Int8, nullptr },
    }, 2 },
    { "UpdateEqualizerEffects", UpdateEqualizerEffects_S2C, {
        { "max_id", 0x08, FType::Int32, nullptr },
        { "type", 0x0C, FType::Int8, nullptr },
    }, 2 },
    { "UpdateEnvironments", UpdateEnvironments_S2C, {
        { "max_id", 0x08, FType::Int32, nullptr },
        { "type", 0x0C, FType::Int8, nullptr },
        { "rebuild_map_geometry", 0x0D, FType::Bool, nullptr },
    }, 3 },
    { "UpdateBlockSoundSets", UpdateBlockSoundSets_S2C, {
        { "max_id", 0x08, FType::Int32, nullptr },
        { "type", 0x0C, FType::Int8, nullptr },
    }, 2 },
    { "UpdateProjectileConfigs", UpdateProjectileConfigs_S2C, {
        { "type", 0x08, FType::Int8, nullptr },
    }, 1 },
    { "UpdateItemQualities", UpdateItemQualities_S2C, {
        { "max_id", 0x08, FType::Int32, nullptr },
        { "type", 0x0C, FType::Int8, nullptr },
    }, 2 },
    { "TrackOrUpdateObjective", TrackOrUpdateObjective_S2C, {
        { "objective", 0x08, FType::Ptr, "Objective" },
    }, 1 },
    { "UpdateBlockTypes", UpdateBlockTypes_S2C, {
        { "max_id", 0x08, FType::Int32, nullptr },
        { "type", 0x0C, FType::Int8, nullptr },
        { "update_block_textures", 0x0D, FType::Bool, nullptr },
        { "update_model_textures", 0x0E, FType::Bool, nullptr },
        { "update_models", 0x0F, FType::Bool, nullptr },
        { "update_map_geometry", 0x10, FType::Bool, nullptr },
    }, 6 },
    { "UpdateEntityStatTypes", UpdateEntityStatTypes_S2C, {
        { "max_id", 0x08, FType::Int32, nullptr },
        { "type", 0x0C, FType::Int8, nullptr },
    }, 2 },
    { "UpdateAudioCategories", UpdateAudioCategories_S2C, {
        { "max_id", 0x08, FType::Int32, nullptr },
        { "type", 0x0C, FType::Int8, nullptr },
    }, 2 },
    { "UpdateBlockGroups", UpdateBlockGroups_S2C, {
        { "type", 0x08, FType::Int8, nullptr },
    }, 1 },
    { "UpdateBlockHitboxes", UpdateBlockHitboxes_S2C, {
        { "max_id", 0x08, FType::Int32, nullptr },
        { "type", 0x0C, FType::Int8, nullptr },
    }, 2 },
    { "UpdateFieldcraftCategories", UpdateFieldcraftCategories_S2C, {
        { "type", 0x08, FType::Int8, nullptr },
    }, 1 },
    { "UpdateObjectiveTask", UpdateObjectiveTask_S2C, {
        { "task", 0x08, FType::Ptr, "ObjectiveTask" },
        { "objective_uuid", 0x10, FType::Ptr, "Guuid" },
        { "task_index", 0x18, FType::Int32, nullptr },
    }, 3 },
    { "UpdateEntityEffects", UpdateEntityEffects_S2C, {
        { "max_id", 0x08, FType::Int32, nullptr },
        { "type", 0x0C, FType::Int8, nullptr },
    }, 2 },
    { "UpdateFluids", UpdateFluids_S2C, {
        { "max_id", 0x08, FType::Int32, nullptr },
        { "type", 0x0C, FType::Int8, nullptr },
    }, 2 },
    { "UpdateHitboxCollisionConfig", UpdateHitboxCollisionConfig_S2C, {
        { "max_id", 0x08, FType::Int32, nullptr },
        { "type", 0x0C, FType::Int8, nullptr },
    }, 2 },
    { "UntrackObjective", UntrackObjective_S2C, {
        { "objective_uuid", 0x08, FType::Ptr, "Guuid" },
    }, 1 },
    { "UpdateRepulsionConfig", UpdateRepulsionConfig_S2C, {
        { "max_id", 0x08, FType::Int32, nullptr },
        { "type", 0x0C, FType::Int8, nullptr },
    }, 2 },
    { "UpdateTagPatterns", UpdateTagPatterns_S2C, {
        { "max_id", 0x08, FType::Int32, nullptr },
        { "type", 0x0C, FType::Int8, nullptr },
    }, 2 },
    { "UpdateParticleSpawners", UpdateParticleSpawners_S2C, {
        { "type", 0x08, FType::Int8, nullptr },
    }, 1 },
    { "UpdateItems", UpdateItems_S2C, {
        { "type", 0x08, FType::Int8, nullptr },
        { "update_models", 0x09, FType::Bool, nullptr },
        { "update_icons", 0x0A, FType::Bool, nullptr },
    }, 3 },
    { "UpdateWeathers", UpdateWeathers_S2C, {
        { "max_id", 0x08, FType::Int32, nullptr },
        { "type", 0x0C, FType::Int8, nullptr },
    }, 2 },
    { "UpdateRecipes", UpdateRecipes_S2C, {
        { "type", 0x08, FType::Int8, nullptr },
    }, 1 },
    { "UpdateBlockSets", UpdateBlockSets_S2C, {
        { "type", 0x08, FType::Int8, nullptr },
    }, 1 },
    { "UpdateItemReticles", UpdateItemReticles_S2C, {
        { "max_id", 0x08, FType::Int32, nullptr },
        { "type", 0x0C, FType::Int8, nullptr },
    }, 2 },
    { "UpdateFluidFX", UpdateFluidFX_S2C, {
        { "max_id", 0x08, FType::Int32, nullptr },
        { "type", 0x0C, FType::Int8, nullptr },
    }, 2 },
    { "UpdateItemSoundSets", UpdateItemSoundSets_S2C, {
        { "max_id", 0x08, FType::Int32, nullptr },
        { "type", 0x0C, FType::Int8, nullptr },
    }, 2 },
    { "CameraShakeEffect", CameraShakeEffect_S2C, {
        { "camera_shake_id", 0x08, FType::Int32, nullptr },
        { "intensity", 0x0C, FType::Float32, nullptr },
        { "mode", 0x10, FType::Int8, nullptr },
    }, 3 },
    { "UpdateInteractions", UpdateInteractions_S2C, {
        { "max_id", 0x08, FType::Int32, nullptr },
        { "type", 0x0C, FType::Int8, nullptr },
    }, 2 },
    { "UpdateBlockParticleSets", UpdateBlockParticleSets_S2C, {
        { "type", 0x08, FType::Int8, nullptr },
    }, 1 },
    { "UpdateSoundSets", UpdateSoundSets_S2C, {
        { "max_id", 0x08, FType::Int32, nullptr },
        { "type", 0x0C, FType::Int8, nullptr },
    }, 2 },
    { "UpdateResourceTypes", UpdateResourceTypes_S2C, {
        { "type", 0x08, FType::Int8, nullptr },
    }, 1 },
    { "UpdateModelvfxs", UpdateModelvfxs_S2C, {
        { "max_id", 0x08, FType::Int32, nullptr },
        { "type", 0x0C, FType::Int8, nullptr },
    }, 2 },
    { "UpdateBlockBreakingDecals", UpdateBlockBreakingDecals_S2C, {
        { "type", 0x08, FType::Int8, nullptr },
    }, 1 },
    { "UpdateTrails", UpdateTrails_S2C, {
        { "type", 0x08, FType::Int8, nullptr },
    }, 1 },
    { "UpdateCameraShake", UpdateCameraShake_S2C, {
        { "type", 0x08, FType::Int8, nullptr },
    }, 1 },
    { "UpdateUnarmedInteractions", UpdateUnarmedInteractions_S2C, {
        { "type", 0x08, FType::Int8, nullptr },
    }, 1 },
    { "ClientReady", ClientReady_C2S, {
        { "ready_for_chunks", 0x08, FType::Bool, nullptr },
        { "ready_for_gameplay", 0x09, FType::Bool, nullptr },
    }, 2 },
    { "SetMovementStates", SetMovementStates_S2C, {
        { "movement_states", 0x08, FType::Ptr, "SavedMovementStates" },
    }, 1 },
    { "LoadHotbar", LoadHotbar_C2S, {
        { "inventory_row", 0x08, FType::Int8, nullptr },
    }, 1 },
    { "DisplayDebug", DisplayDebug_S2C, {
        { "matrix", 0x08, FType::Ptr, "Array<float>" },
        { "color", 0x10, FType::Ptr, "Vector3f" },
        { "frustum_projection", 0x18, FType::Ptr, "Array<float>" },
        { "time", 0x20, FType::Float32, nullptr },
        { "opacity", 0x24, FType::Float32, nullptr },
        { "shape", 0x28, FType::Int8, nullptr },
        { "flags", 0x29, FType::Int8, nullptr },
    }, 7 },
    { "SetClientId", SetClientId_S2C, {
        { "client_id", 0x08, FType::Int32, nullptr },
    }, 1 },
    { "UpdateMovementSettings", UpdateMovementSettings_S2C, {
        { "movement_settings", 0x08, FType::Ptr, "MovementSettings" },
    }, 1 },
    { "ClearDebugShapes", ClearDebugShapes_S2C, {
    }, 0 },
    { "SyncPlayerPreferences", SyncPlayerPreferences_C2S, {
        { "show_entity_markers", 0x08, FType::Bool, nullptr },
        { "armor_items_preferred_pickup_location", 0x09, FType::Int8, nullptr },
        { "weapon_and_tool_items_preferred_pickup_location", 0x0A, FType::Int8, nullptr },
        { "usable_items_items_preferred_pickup_location", 0x0B, FType::Int8, nullptr },
        { "solid_block_items_preferred_pickup_location", 0x0C, FType::Int8, nullptr },
        { "misc_items_preferred_pickup_location", 0x0D, FType::Int8, nullptr },
        { "allow_n_p_c_detection", 0x0E, FType::Bool, nullptr },
        { "respond_to_hit", 0x0F, FType::Bool, nullptr },
        { "hide_helmet", 0x10, FType::Bool, nullptr },
        { "hide_cuirass", 0x11, FType::Bool, nullptr },
        { "hide_gauntlets", 0x12, FType::Bool, nullptr },
        { "hide_pants", 0x13, FType::Bool, nullptr },
    }, 12 },
    { "ClientMovement", ClientMovement_C2S, {
        { "movement_states", 0x08, FType::Ptr, "MovementStates" },
        { "relative_position", 0x10, FType::Ptr, "HalfFloatPosition" },
        { "absolute_position", 0x18, FType::Ptr, "Position" },
        { "body_orientation", 0x20, FType::Ptr, "Direction" },
        { "look_orientation", 0x28, FType::Ptr, "Direction" },
        { "teleport_ack", 0x30, FType::Ptr, "TeleportAck" },
        { "wish_movement", 0x38, FType::Ptr, "Position" },
        { "velocity", 0x40, FType::Ptr, "Vector3d" },
        { "rider_movement_states", 0x48, FType::Ptr, "MovementStates" },
        { "mounted_to", 0x50, FType::Int32, nullptr },
    }, 10 },
    { "SetBlockPlacementOverride", SetBlockPlacementOverride_S2C, {
        { "enabled", 0x08, FType::Bool, nullptr },
    }, 1 },
    { "SetGameMode", SetGameMode_S2C, {
        { "game_mode", 0x08, FType::Int8, nullptr },
    }, 1 },
    { "MouseInteraction", MouseInteraction_C2S, {
        { "item_in_hand_id", 0x08, FType::Ptr, "String" },
        { "screen_point", 0x10, FType::Ptr, "Vector2f" },
        { "mouse_button", 0x18, FType::Ptr, "MouseButtonEvent" },
        { "mouse_motion", 0x20, FType::Ptr, "MouseMotionEvent" },
        { "world_interaction", 0x28, FType::Ptr, "WorldInteraction" },
        { "client_timestamp", 0x30, FType::Int64, nullptr },
        { "active_slot", 0x38, FType::Int32, nullptr },
    }, 7 },
    { "ReticleEvent", ReticleEvent_S2C, {
        { "event_index", 0x08, FType::Int32, nullptr },
    }, 1 },
    { "SaveHotbar", SaveHotbar_C2S, {
        { "inventory_row", 0x08, FType::Int8, nullptr },
    }, 1 },
    { "ClientTeleport", ClientTeleport_S2C, {
        { "model_transform", 0x08, FType::Ptr, "ModelTransform" },
        { "teleport_id", 0x10, FType::Int8, nullptr },
        { "reset_velocity", 0x11, FType::Bool, nullptr },
    }, 3 },
    { "JoinWorld", JoinWorld_S2C, {
        { "world_uuid", 0x08, FType::Ptr, "Guuid" },
        { "clear_world", 0x10, FType::Bool, nullptr },
        { "fade_in_out", 0x11, FType::Bool, nullptr },
    }, 3 },
    { "RemoveMapMarker", RemoveMapMarker_C2S, {
        { "marker_id", 0x08, FType::Ptr, "String" },
    }, 1 },
    { "DamageInfo", DamageInfo_S2C, {
        { "damage_source_position", 0x08, FType::Ptr, "Vector3d" },
        { "damage_cause", 0x10, FType::Ptr, "DamageCause" },
        { "damage_amount", 0x18, FType::Float32, nullptr },
    }, 3 },
    { "UpdateMemoriesFeatureStatus", UpdateMemoriesFeatureStatus_S2C, {
        { "is_feature_unlocked", 0x08, FType::Bool, nullptr },
    }, 1 },
    { "ClientPlaceBlock", ClientPlaceBlock_C2S, {
        { "position", 0x08, FType::Ptr, "BlockPosition" },
        { "rotation", 0x10, FType::Ptr, "BlockRotation" },
        { "placed_block_id", 0x18, FType::Int32, nullptr },
        { "quick_replace", 0x1C, FType::Bool, nullptr },
    }, 4 },
    { "OpenWindow", OpenWindow_S2C, {
        { "window_data", 0x08, FType::Ptr, "String" },
        { "inventory", 0x10, FType::Ptr, "InventorySection" },
        { "extra_resources", 0x18, FType::Ptr, "ExtraResources" },
        { "id", 0x20, FType::Int32, nullptr },
        { "window_type", 0x24, FType::Int8, nullptr },
    }, 5 },
    { "CloseWindow", CloseWindow_BI, {
        { "id", 0x08, FType::Int32, nullptr },
    }, 1 },
    { "SendWindowAction", SendWindowAction_C2S, {
        { "action", 0x08, FType::Ptr, "WindowAction" },
        { "id", 0x10, FType::Int32, nullptr },
    }, 2 },
    { "ClientOpenWindow", ClientOpenWindow_C2S, {
        { "type", 0x08, FType::Int8, nullptr },
    }, 1 },
    { "UpdateWindow", UpdateWindow_S2C, {
        { "window_data", 0x08, FType::Ptr, "String" },
        { "inventory", 0x10, FType::Ptr, "InventorySection" },
        { "extra_resources", 0x18, FType::Ptr, "ExtraResources" },
        { "id", 0x20, FType::Int32, nullptr },
    }, 4 },
    { "BuilderToolSetNPCDebug", BuilderToolSetNPCDebug_C2S, {
        { "entity_id", 0x08, FType::Int32, nullptr },
        { "enabled", 0x0C, FType::Bool, nullptr },
    }, 2 },
    { "BuilderToolRotateClipboard", BuilderToolRotateClipboard_C2S, {
        { "angle", 0x08, FType::Int32, nullptr },
        { "axis", 0x0C, FType::Int8, nullptr },
    }, 2 },
    { "BuilderToolSetEntityTransform", BuilderToolSetEntityTransform_C2S, {
        { "model_transform", 0x08, FType::Ptr, "ModelTransform" },
        { "entity_id", 0x10, FType::Int32, nullptr },
    }, 2 },
    { "BuilderToolSetEntityLight", BuilderToolSetEntityLight_C2S, {
        { "light", 0x08, FType::Ptr, "ColorLight" },
        { "entity_id", 0x10, FType::Int32, nullptr },
    }, 2 },
    { "BuilderToolSelectionToolReplyWithClipboard", BuilderToolSelectionToolReplyWithClipboard_S2C, {
    }, 0 },
    { "BuilderToolLaserPointer", BuilderToolLaserPointer_S2C, {
        { "player_network_id", 0x08, FType::Int32, nullptr },
        { "start_x", 0x0C, FType::Float32, nullptr },
        { "start_y", 0x10, FType::Float32, nullptr },
        { "start_z", 0x14, FType::Float32, nullptr },
        { "end_x", 0x18, FType::Float32, nullptr },
        { "end_y", 0x1C, FType::Float32, nullptr },
        { "end_z", 0x20, FType::Float32, nullptr },
        { "color", 0x24, FType::Int32, nullptr },
        { "duration_ms", 0x28, FType::Int32, nullptr },
    }, 9 },
    { "BuilderToolStackArea", BuilderToolStackArea_C2S, {
        { "selection_min", 0x08, FType::Ptr, "BlockPosition" },
        { "selection_max", 0x10, FType::Ptr, "BlockPosition" },
        { "x_normal", 0x18, FType::Int32, nullptr },
        { "y_normal", 0x1C, FType::Int32, nullptr },
        { "z_normal", 0x20, FType::Int32, nullptr },
        { "num_stacks", 0x24, FType::Int32, nullptr },
    }, 6 },
    { "BuilderToolSetEntityScale", BuilderToolSetEntityScale_C2S, {
        { "entity_id", 0x08, FType::Int32, nullptr },
        { "scale", 0x0C, FType::Float32, nullptr },
    }, 2 },
    { "BuilderToolArgUpdate", BuilderToolArgUpdate_C2S, {
        { "id", 0x08, FType::Ptr, "String" },
        { "value", 0x10, FType::Ptr, "String" },
        { "token", 0x18, FType::Int32, nullptr },
        { "section", 0x1C, FType::Int32, nullptr },
        { "slot", 0x20, FType::Int32, nullptr },
    }, 5 },
    { "BuilderToolHideAnchors", BuilderToolHideAnchors_S2C, {
    }, 0 },
    { "BuilderToolResetClipboardRotation", BuilderToolResetClipboardRotation_C2S, {
    }, 0 },
    { "BuilderToolEntityAction", BuilderToolEntityAction_C2S, {
        { "entity_id", 0x08, FType::Int32, nullptr },
        { "action", 0x0C, FType::Int8, nullptr },
    }, 2 },
    { "BuilderToolOnUseInteraction", BuilderToolOnUseInteraction_C2S, {
        { "x", 0x08, FType::Int32, nullptr },
        { "y", 0x0C, FType::Int32, nullptr },
        { "z", 0x10, FType::Int32, nullptr },
        { "offset_for_paint_mode_x", 0x14, FType::Int32, nullptr },
        { "offset_for_paint_mode_y", 0x18, FType::Int32, nullptr },
        { "offset_for_paint_mode_z", 0x1C, FType::Int32, nullptr },
        { "max_length_tool_ignore_history", 0x20, FType::Int32, nullptr },
        { "raycast_origin_x", 0x24, FType::Float32, nullptr },
        { "raycast_origin_y", 0x28, FType::Float32, nullptr },
        { "raycast_origin_z", 0x2C, FType::Float32, nullptr },
        { "raycast_direction_x", 0x30, FType::Float32, nullptr },
        { "raycast_direction_y", 0x34, FType::Float32, nullptr },
        { "raycast_direction_z", 0x38, FType::Float32, nullptr },
        { "undo_group_size", 0x3C, FType::Int32, nullptr },
        { "type", 0x40, FType::Int8, nullptr },
        { "is_alt_play_sculpt_brush_mod_down", 0x41, FType::Bool, nullptr },
        { "is_hold_down_interaction", 0x42, FType::Bool, nullptr },
        { "is_do_server_raytrace_for_position", 0x43, FType::Bool, nullptr },
        { "is_show_edit_notifications", 0x44, FType::Bool, nullptr },
    }, 19 },
    { "PrefabSetAnchor", PrefabSetAnchor_C2S, {
        { "x", 0x08, FType::Int32, nullptr },
        { "y", 0x0C, FType::Int32, nullptr },
        { "z", 0x10, FType::Int32, nullptr },
    }, 3 },
    { "BuilderToolSetTransformationModeState", BuilderToolSetTransformationModeState_C2S, {
        { "enabled", 0x08, FType::Bool, nullptr },
    }, 1 },
    { "BuilderToolsSetSoundSet", BuilderToolsSetSoundSet_S2C, {
        { "sound_set_index", 0x08, FType::Int32, nullptr },
    }, 1 },
    { "BuilderToolExtrudeAction", BuilderToolExtrudeAction_C2S, {
        { "x", 0x08, FType::Int32, nullptr },
        { "y", 0x0C, FType::Int32, nullptr },
        { "z", 0x10, FType::Int32, nullptr },
        { "x_normal", 0x14, FType::Int32, nullptr },
        { "y_normal", 0x18, FType::Int32, nullptr },
        { "z_normal", 0x1C, FType::Int32, nullptr },
    }, 6 },
    { "BuilderToolSetEntityPickupEnabled", BuilderToolSetEntityPickupEnabled_C2S, {
        { "entity_id", 0x08, FType::Int32, nullptr },
        { "enabled", 0x0C, FType::Bool, nullptr },
    }, 2 },
    { "BuilderToolPasteClipboard", BuilderToolPasteClipboard_C2S, {
        { "x", 0x08, FType::Int32, nullptr },
        { "y", 0x0C, FType::Int32, nullptr },
        { "z", 0x10, FType::Int32, nullptr },
    }, 3 },
    { "BuilderToolSelectionToolAskForClipboard", BuilderToolSelectionToolAskForClipboard_C2S, {
    }, 0 },
    { "PrefabUnselectPrefab", PrefabUnselectPrefab_C2S, {
    }, 0 },
    { "BuilderToolLineAction", BuilderToolLineAction_C2S, {
        { "x_start", 0x08, FType::Int32, nullptr },
        { "y_start", 0x0C, FType::Int32, nullptr },
        { "z_start", 0x10, FType::Int32, nullptr },
        { "x_end", 0x14, FType::Int32, nullptr },
        { "y_end", 0x18, FType::Int32, nullptr },
        { "z_end", 0x1C, FType::Int32, nullptr },
    }, 6 },
    { "BuilderToolGeneralAction", BuilderToolGeneralAction_C2S, {
        { "action", 0x08, FType::Int8, nullptr },
    }, 1 },
    { "BuilderToolSelectionTransform", BuilderToolSelectionTransform_C2S, {
        { "rotation", 0x08, FType::Ptr, "Quaternionfc" },
        { "translation_offset", 0x10, FType::Ptr, "BlockPosition" },
        { "initial_selection_min", 0x18, FType::Ptr, "BlockPosition" },
        { "initial_selection_max", 0x20, FType::Ptr, "BlockPosition" },
        { "initial_rotation_origin", 0x28, FType::Ptr, "Vector3f" },
        { "initial_paste_point_for_clipboard_paste", 0x30, FType::Ptr, "BlockPosition" },
        { "cut_original", 0x38, FType::Bool, nullptr },
        { "apply_transformation_to_selection_min_max", 0x39, FType::Bool, nullptr },
        { "is_exiting_transform_mode", 0x3A, FType::Bool, nullptr },
    }, 9 },
    { "BuilderToolShowAnchor", BuilderToolShowAnchor_S2C, {
        { "x", 0x08, FType::Int32, nullptr },
        { "y", 0x0C, FType::Int32, nullptr },
        { "z", 0x10, FType::Int32, nullptr },
    }, 3 },
    { "BuilderToolSetEntityCollision", BuilderToolSetEntityCollision_C2S, {
        { "collision_type", 0x08, FType::Ptr, "String" },
        { "entity_id", 0x10, FType::Int32, nullptr },
    }, 2 },
    { "BuilderToolSelectionUpdate", BuilderToolSelectionUpdate_C2S, {
        { "x_min", 0x08, FType::Int32, nullptr },
        { "y_min", 0x0C, FType::Int32, nullptr },
        { "z_min", 0x10, FType::Int32, nullptr },
        { "x_max", 0x14, FType::Int32, nullptr },
        { "y_max", 0x18, FType::Int32, nullptr },
        { "z_max", 0x1C, FType::Int32, nullptr },
    }, 6 },
    { "UpdateEnvironmentMusic", UpdateEnvironmentMusic_S2C, {
        { "environment_index", 0x08, FType::Int32, nullptr },
    }, 1 },
    { "PlaySoundEventEntity", PlaySoundEventEntity_S2C, {
        { "sound_event_index", 0x08, FType::Int32, nullptr },
        { "network_id", 0x0C, FType::Int32, nullptr },
        { "volume_modifier", 0x10, FType::Float32, nullptr },
        { "pitch_modifier", 0x14, FType::Float32, nullptr },
    }, 4 },
    { "SetChunkTintmap", SetChunkTintmap_S2C, {
        { "tintmap", 0x08, FType::Ptr, "Array<Byte>" },
        { "x", 0x10, FType::Int32, nullptr },
        { "z", 0x14, FType::Int32, nullptr },
    }, 3 },
    { "PlaySoundEvent2D", PlaySoundEvent2D_S2C, {
        { "sound_event_index", 0x08, FType::Int32, nullptr },
        { "volume_modifier", 0x0C, FType::Float32, nullptr },
        { "pitch_modifier", 0x10, FType::Float32, nullptr },
        { "category", 0x14, FType::Int8, nullptr },
    }, 4 },
    { "PlaySoundEvent3D", PlaySoundEvent3D_S2C, {
        { "position", 0x08, FType::Ptr, "Position" },
        { "sound_event_index", 0x10, FType::Int32, nullptr },
        { "volume_modifier", 0x14, FType::Float32, nullptr },
        { "pitch_modifier", 0x18, FType::Float32, nullptr },
        { "category", 0x1C, FType::Int8, nullptr },
    }, 5 },
    { "UpdateSunSettings", UpdateSunSettings_S2C, {
        { "height_percentage", 0x08, FType::Float32, nullptr },
        { "angle_radians", 0x0C, FType::Float32, nullptr },
    }, 2 },
    { "SetChunkHeightmap", SetChunkHeightmap_S2C, {
        { "heightmap", 0x08, FType::Ptr, "Array<Byte>" },
        { "x", 0x10, FType::Int32, nullptr },
        { "z", 0x14, FType::Int32, nullptr },
    }, 3 },
    { "UpdateTimeSettings", UpdateTimeSettings_S2C, {
        { "daytime_duration_seconds", 0x08, FType::Int32, nullptr },
        { "nighttime_duration_seconds", 0x0C, FType::Int32, nullptr },
        { "total_moon_phases", 0x10, FType::Int8, nullptr },
        { "time_paused", 0x11, FType::Bool, nullptr },
    }, 4 },
    { "ServerSetBlocks", ServerSetBlocks_S2C, {
        { "x", 0x08, FType::Int32, nullptr },
        { "y", 0x0C, FType::Int32, nullptr },
        { "z", 0x10, FType::Int32, nullptr },
    }, 3 },
    { "UnloadChunk", UnloadChunk_S2C, {
        { "chunk_x", 0x08, FType::Int32, nullptr },
        { "chunk_z", 0x0C, FType::Int32, nullptr },
    }, 2 },
    { "SetChunkEnvironments", SetChunkEnvironments_S2C, {
        { "environments", 0x08, FType::Ptr, "Array<Byte>" },
        { "x", 0x10, FType::Int32, nullptr },
        { "z", 0x14, FType::Int32, nullptr },
    }, 3 },
    { "SetFluids", SetFluids_S2C, {
        { "data", 0x08, FType::Ptr, "Array<Byte>" },
        { "x", 0x10, FType::Int32, nullptr },
        { "y", 0x14, FType::Int32, nullptr },
        { "z", 0x18, FType::Int32, nullptr },
    }, 4 },
    { "UpdateTime", UpdateTime_S2C, {
        { "game_time", 0x08, FType::Ptr, "InstantData" },
    }, 1 },
    { "SpawnParticleSystem", SpawnParticleSystem_S2C, {
        { "particle_system_id", 0x08, FType::Ptr, "String" },
        { "position", 0x10, FType::Ptr, "Position" },
        { "rotation", 0x18, FType::Ptr, "Direction" },
        { "color", 0x20, FType::Ptr, "Color" },
        { "scale", 0x28, FType::Float32, nullptr },
    }, 5 },
    { "UpdateEditorTimeOverride", UpdateEditorTimeOverride_S2C, {
        { "game_time", 0x08, FType::Ptr, "InstantData" },
        { "paused", 0x10, FType::Bool, nullptr },
    }, 2 },
    { "SetPaused", SetPaused_C2S, {
        { "paused", 0x08, FType::Bool, nullptr },
    }, 1 },
    { "UpdateSleepState", UpdateSleepState_S2C, {
        { "clock", 0x08, FType::Ptr, "SleepClock" },
        { "multiplayer", 0x10, FType::Ptr, "SleepMultiplayer" },
        { "gray_fade", 0x18, FType::Bool, nullptr },
        { "sleep_ui", 0x19, FType::Bool, nullptr },
    }, 4 },
    { "UpdateBlockDamage", UpdateBlockDamage_S2C, {
        { "block_position", 0x08, FType::Ptr, "BlockPosition" },
        { "damage", 0x10, FType::Float32, nullptr },
        { "delta", 0x14, FType::Float32, nullptr },
    }, 3 },
    { "SpawnBlockParticleSystem", SpawnBlockParticleSystem_S2C, {
        { "position", 0x08, FType::Ptr, "Position" },
        { "block_id", 0x10, FType::Int32, nullptr },
        { "particle_type", 0x14, FType::Int8, nullptr },
    }, 3 },
    { "UpdatePostFxSettings", UpdatePostFxSettings_S2C, {
        { "global_intensity", 0x08, FType::Float32, nullptr },
        { "power", 0x0C, FType::Float32, nullptr },
        { "sunshaft_scale", 0x10, FType::Float32, nullptr },
        { "sun_intensity", 0x14, FType::Float32, nullptr },
        { "sunshaft_intensity", 0x18, FType::Float32, nullptr },
    }, 5 },
    { "SetChunk", SetChunk_S2C, {
        { "local_light", 0x08, FType::Ptr, "Array<Byte>" },
        { "global_light", 0x10, FType::Ptr, "Array<Byte>" },
        { "data", 0x18, FType::Ptr, "Array<Byte>" },
        { "x", 0x20, FType::Int32, nullptr },
        { "y", 0x24, FType::Int32, nullptr },
        { "z", 0x28, FType::Int32, nullptr },
    }, 6 },
    { "PlaySoundEventLocalPlayer", PlaySoundEventLocalPlayer_S2C, {
        { "local_sound_event_index", 0x08, FType::Int32, nullptr },
        { "world_sound_event_index", 0x0C, FType::Int32, nullptr },
        { "volume_modifier", 0x10, FType::Float32, nullptr },
        { "pitch_modifier", 0x14, FType::Float32, nullptr },
        { "category", 0x18, FType::Int8, nullptr },
    }, 5 },
    { "ServerSetBlock", ServerSetBlock_S2C, {
        { "x", 0x08, FType::Int32, nullptr },
        { "y", 0x0C, FType::Int32, nullptr },
        { "z", 0x10, FType::Int32, nullptr },
        { "block_id", 0x14, FType::Int32, nullptr },
        { "filler", 0x18, FType::Int16, nullptr },
        { "rotation", 0x1A, FType::Int8, nullptr },
    }, 6 },
    { "UpdateEditorWeatherOverride", UpdateEditorWeatherOverride_S2C, {
        { "weather_index", 0x08, FType::Int32, nullptr },
    }, 1 },
    { "UpdateWeather", UpdateWeather_S2C, {
        { "weather_index", 0x08, FType::Int32, nullptr },
        { "transition_seconds", 0x0C, FType::Float32, nullptr },
    }, 2 },
    { "ClearEditorTimeOverride", ClearEditorTimeOverride_S2C, {
    }, 0 },
    { "ServerSetFluids", ServerSetFluids_S2C, {
        { "x", 0x08, FType::Int32, nullptr },
        { "y", 0x0C, FType::Int32, nullptr },
        { "z", 0x10, FType::Int32, nullptr },
    }, 3 },
    { "ServerSetFluid", ServerSetFluid_S2C, {
        { "x", 0x08, FType::Int32, nullptr },
        { "y", 0x0C, FType::Int32, nullptr },
        { "z", 0x10, FType::Int32, nullptr },
        { "fluid_id", 0x14, FType::Int32, nullptr },
        { "fluid_level", 0x18, FType::Int8, nullptr },
    }, 5 },
    { "ServerSetPaused", ServerSetPaused_S2C, {
        { "paused", 0x08, FType::Bool, nullptr },
    }, 1 },
    { "VoiceData", VoiceData_C2S, {
        { "opus_data", 0x08, FType::Ptr, "Array<Byte>" },
        { "timestamp", 0x10, FType::Int32, nullptr },
        { "sequence_number", 0x14, FType::Int16, nullptr },
    }, 3 },
    { "VoiceConfig", VoiceConfig_S2C, {
        { "sample_rate", 0x08, FType::Int32, nullptr },
        { "max_hearing_distance", 0x0C, FType::Float32, nullptr },
        { "reference_distance", 0x10, FType::Float32, nullptr },
        { "voice_enabled", 0x14, FType::Bool, nullptr },
        { "codec", 0x15, FType::Int8, nullptr },
        { "channels", 0x16, FType::Int8, nullptr },
        { "supports_voice_stream", 0x17, FType::Bool, nullptr },
        { "max_packets_per_second", 0x18, FType::Int8, nullptr },
    }, 8 },
    { "RelayedVoiceData", RelayedVoiceData_S2C, {
        { "speaker_position", 0x08, FType::Ptr, "Position" },
        { "opus_data", 0x10, FType::Ptr, "Array<Byte>" },
        { "speaker_id", 0x18, FType::Ptr, "Guuid" },
        { "entity_id", 0x20, FType::Int32, nullptr },
        { "timestamp", 0x24, FType::Int32, nullptr },
        { "sequence_number", 0x28, FType::Int16, nullptr },
        { "speaker_is_underwater", 0x2A, FType::Bool, nullptr },
    }, 7 },
    { "RequestFlyCameraMode", RequestFlyCameraMode_C2S, {
        { "entering", 0x08, FType::Bool, nullptr },
    }, 1 },
    { "SetServerCamera", SetServerCamera_S2C, {
        { "camera_settings", 0x08, FType::Ptr, "ServerCameraSettings" },
        { "client_camera_view", 0x10, FType::Int8, nullptr },
        { "is_locked", 0x11, FType::Bool, nullptr },
    }, 3 },
    { "SetFlyCameraMode", SetFlyCameraMode_S2C, {
        { "entering", 0x08, FType::Bool, nullptr },
    }, 1 },
    { "CustomHud", CustomHud_S2C, {
        { "clear", 0x08, FType::Bool, nullptr },
    }, 1 },
    { "EditorBlocksChange", EditorBlocksChange_S2C, {
        { "selection", 0x08, FType::Ptr, "EditorSelection" },
        { "blocks_count", 0x10, FType::Int32, nullptr },
        { "advanced_preview", 0x14, FType::Bool, nullptr },
        { "skip_preview_rebuild", 0x15, FType::Bool, nullptr },
    }, 4 },
    { "AddToServerPlayerList", AddToServerPlayerList_S2C, {
    }, 0 },
    { "UpdateVisibleHudComponents", UpdateVisibleHudComponents_S2C, {
        { "visible_components", 0x08, FType::Ptr, "Array<HudComponent>" },
    }, 1 },
    { "ServerInfo", ServerInfo_S2C, {
        { "server_name", 0x08, FType::Ptr, "String" },
        { "motd", 0x10, FType::Ptr, "String" },
        { "fallback_server", 0x18, FType::Ptr, "HostAddress" },
        { "max_players", 0x20, FType::Int32, nullptr },
    }, 4 },
    { "ShowEventTitle", ShowEventTitle_S2C, {
        { "icon", 0x08, FType::Ptr, "String" },
        { "primary_title", 0x10, FType::Ptr, "FormattedMessage" },
        { "secondary_title", 0x18, FType::Ptr, "FormattedMessage" },
        { "fade_in_duration", 0x20, FType::Float32, nullptr },
        { "fade_out_duration", 0x24, FType::Float32, nullptr },
        { "duration", 0x28, FType::Float32, nullptr },
        { "is_major", 0x2C, FType::Bool, nullptr },
    }, 7 },
    { "KillFeedMessage", KillFeedMessage_S2C, {
        { "killer", 0x08, FType::Ptr, "FormattedMessage" },
        { "decedent", 0x10, FType::Ptr, "FormattedMessage" },
        { "icon", 0x18, FType::Ptr, "String" },
    }, 3 },
    { "RemoveFromServerPlayerList", RemoveFromServerPlayerList_S2C, {
        { "players", 0x08, FType::Ptr, "Array<Guuid>" },
    }, 1 },
    { "CustomPageEvent", CustomPageEvent_C2S, {
        { "data", 0x08, FType::Ptr, "String" },
        { "type", 0x10, FType::Int8, nullptr },
    }, 2 },
    { "ServerMessage", ServerMessage_S2C, {
        { "message", 0x08, FType::Ptr, "FormattedMessage" },
        { "type", 0x10, FType::Int8, nullptr },
    }, 2 },
    { "UpdateLanguage", UpdateLanguage_C2S, {
        { "language", 0x08, FType::Ptr, "String" },
    }, 1 },
    { "CustomPage", CustomPage_S2C, {
        { "key", 0x08, FType::Ptr, "String" },
        { "is_initial", 0x10, FType::Bool, nullptr },
        { "clear", 0x11, FType::Bool, nullptr },
        { "lifetime", 0x12, FType::Int8, nullptr },
    }, 4 },
    { "UpdateServerPlayerListPing", UpdateServerPlayerListPing_S2C, {
    }, 0 },
    { "Notification", Notification_S2C, {
        { "message", 0x08, FType::Ptr, "FormattedMessage" },
        { "secondary_message", 0x10, FType::Ptr, "FormattedMessage" },
        { "icon", 0x18, FType::Ptr, "String" },
        { "item", 0x20, FType::Ptr, "ItemWithAllMetadata" },
        { "style", 0x28, FType::Int8, nullptr },
    }, 5 },
    { "UpdatePortal", UpdatePortal_S2C, {
        { "state", 0x08, FType::Ptr, "PortalState" },
        { "definition", 0x10, FType::Ptr, "PortalDef" },
    }, 2 },
    { "UpdateServerPlayerList", UpdateServerPlayerList_S2C, {
    }, 0 },
    { "OpenChatWithCommand", OpenChatWithCommand_S2C, {
        { "command", 0x08, FType::Ptr, "String" },
    }, 1 },
    { "UpdateKnownRecipes", UpdateKnownRecipes_S2C, {
    }, 0 },
    { "UpdateAnchorUI", UpdateAnchorUI_S2C, {
        { "anchor_id", 0x08, FType::Ptr, "String" },
        { "clear", 0x10, FType::Bool, nullptr },
    }, 2 },
    { "ChatMessage", ChatMessage_C2S, {
        { "message", 0x08, FType::Ptr, "String" },
    }, 1 },
    { "ResetUserInterfaceState", ResetUserInterfaceState_S2C, {
    }, 0 },
    { "SetPage", SetPage_S2C, {
        { "page", 0x08, FType::Int8, nullptr },
        { "can_close_through_interaction", 0x09, FType::Bool, nullptr },
    }, 2 },
    { "HideEventTitle", HideEventTitle_S2C, {
        { "fade_out_duration", 0x08, FType::Float32, nullptr },
    }, 1 },
    { "WorldSavingStatus", WorldSavingStatus_S2C, {
        { "is_world_saving", 0x08, FType::Bool, nullptr },
    }, 1 },
    { "DropItemStack", DropItemStack_C2S, {
        { "inventory_section_id", 0x08, FType::Int32, nullptr },
        { "slot_id", 0x0C, FType::Int32, nullptr },
        { "quantity", 0x10, FType::Int32, nullptr },
    }, 3 },
    { "SwitchHotbarBlockSet", SwitchHotbarBlockSet_C2S, {
        { "item_id", 0x08, FType::Ptr, "String" },
    }, 1 },
    { "UpdatePlayerInventory", UpdatePlayerInventory_S2C, {
        { "storage", 0x08, FType::Ptr, "InventorySection" },
        { "armor", 0x10, FType::Ptr, "InventorySection" },
        { "hotbar", 0x18, FType::Ptr, "InventorySection" },
        { "utility", 0x20, FType::Ptr, "InventorySection" },
        { "tools", 0x28, FType::Ptr, "InventorySection" },
        { "backpack", 0x30, FType::Ptr, "InventorySection" },
    }, 6 },
    { "SmartMoveItemStack", SmartMoveItemStack_BI, {
        { "from_section_id", 0x08, FType::Int32, nullptr },
        { "from_slot_id", 0x0C, FType::Int32, nullptr },
        { "quantity", 0x10, FType::Int32, nullptr },
        { "move_type", 0x14, FType::Int8, nullptr },
    }, 4 },
    { "DropCreativeItem", DropCreativeItem_C2S, {
        { "item", 0x08, FType::Ptr, "ItemQuantity" },
    }, 1 },
    { "InventoryAction", InventoryAction_C2S, {
        { "inventory_section_id", 0x08, FType::Int32, nullptr },
        { "inventory_action_type", 0x0C, FType::Int8, nullptr },
        { "action_data", 0x0D, FType::Int8, nullptr },
    }, 3 },
    { "MoveItemStack", MoveItemStack_C2S, {
        { "from_section_id", 0x08, FType::Int32, nullptr },
        { "from_slot_id", 0x0C, FType::Int32, nullptr },
        { "quantity", 0x10, FType::Int32, nullptr },
        { "to_section_id", 0x14, FType::Int32, nullptr },
        { "to_slot_id", 0x18, FType::Int32, nullptr },
    }, 5 },
    { "SmartGiveCreativeItem", SmartGiveCreativeItem_C2S, {
        { "item", 0x08, FType::Ptr, "ItemQuantity" },
        { "move_type", 0x10, FType::Int8, nullptr },
    }, 2 },
    { "SetActiveSlot", SetActiveSlot_BI, {
        { "inventory_section_id", 0x08, FType::Int32, nullptr },
        { "active_slot", 0x0C, FType::Int32, nullptr },
    }, 2 },
    { "SetCreativeItem", SetCreativeItem_C2S, {
        { "item", 0x08, FType::Ptr, "ItemQuantity" },
        { "inventory_section_id", 0x10, FType::Int32, nullptr },
        { "slot_id", 0x14, FType::Int32, nullptr },
        { "override", 0x18, FType::Bool, nullptr },
    }, 4 },
    { "AssetEditorJsonAssetUpdated", AssetEditorJsonAssetUpdated_S2C, {
        { "path", 0x08, FType::Ptr, "AssetPath" },
    }, 1 },
    { "AssetEditorExportDeleteAssets", AssetEditorExportDeleteAssets_S2C, {
    }, 0 },
    { "AssetEditorAssetListUpdate", AssetEditorAssetListUpdate_S2C, {
        { "pack", 0x08, FType::Ptr, "String" },
    }, 1 },
    { "FailureReply", FailureReply_BI, {
        { "message", 0x08, FType::Ptr, "FormattedMessage" },
        { "token", 0x10, FType::Int32, nullptr },
    }, 2 },
    { "AssetEditorSelectAsset", AssetEditorSelectAsset_C2S, {
        { "path", 0x08, FType::Ptr, "AssetPath" },
    }, 1 },
    { "AssetEditorAssetListSetup", AssetEditorAssetListSetup_S2C, {
        { "pack", 0x08, FType::Ptr, "String" },
        { "is_read_only", 0x10, FType::Bool, nullptr },
        { "can_be_deleted", 0x11, FType::Bool, nullptr },
        { "tree", 0x12, FType::Int8, nullptr },
    }, 4 },
    { "AssetEditorRenameDirectory", AssetEditorRenameDirectory_C2S, {
        { "path", 0x08, FType::Ptr, "AssetPath" },
        { "new_path", 0x10, FType::Ptr, "AssetPath" },
        { "token", 0x18, FType::Int32, nullptr },
    }, 3 },
    { "AssetEditorFetchAsset", AssetEditorFetchAsset_C2S, {
        { "path", 0x08, FType::Ptr, "AssetPath" },
        { "token", 0x10, FType::Int32, nullptr },
        { "is_from_opened_tab", 0x14, FType::Bool, nullptr },
    }, 3 },
    { "SuccessReply", SuccessReply_BI, {
        { "message", 0x08, FType::Ptr, "FormattedMessage" },
        { "token", 0x10, FType::Int32, nullptr },
    }, 2 },
    { "AssetEditorExportComplete", AssetEditorExportComplete_S2C, {
    }, 0 },
    { "AssetEditorFetchJsonAssetWithParentsReply", AssetEditorFetchJsonAssetWithParentsReply_S2C, {
        { "token", 0x08, FType::Int32, nullptr },
    }, 1 },
    { "AssetEditorInitialize", AssetEditorInitialize_C2S, {
    }, 0 },
    { "AssetEditorDeleteDirectory", AssetEditorDeleteDirectory_C2S, {
        { "path", 0x08, FType::Ptr, "AssetPath" },
        { "token", 0x10, FType::Int32, nullptr },
    }, 2 },
    { "AssetEditorUpdateJsonAsset", AssetEditorUpdateJsonAsset_C2S, {
        { "asset_type", 0x08, FType::Ptr, "String" },
        { "path", 0x10, FType::Ptr, "AssetPath" },
        { "token", 0x18, FType::Int32, nullptr },
        { "asset_index", 0x1C, FType::Int32, nullptr },
    }, 4 },
    { "AssetEditorFetchJsonAssetWithParents", AssetEditorFetchJsonAssetWithParents_C2S, {
        { "path", 0x08, FType::Ptr, "AssetPath" },
        { "token", 0x10, FType::Int32, nullptr },
        { "is_from_opened_tab", 0x14, FType::Bool, nullptr },
    }, 3 },
    { "AssetEditorAssetUpdated", AssetEditorAssetUpdated_S2C, {
        { "path", 0x08, FType::Ptr, "AssetPath" },
        { "data", 0x10, FType::Ptr, "Array<Byte>" },
    }, 2 },
    { "AssetEditorSetGameTime", AssetEditorSetGameTime_C2S, {
        { "game_time", 0x08, FType::Ptr, "InstantData" },
        { "paused", 0x10, FType::Bool, nullptr },
    }, 2 },
    { "AssetEditorFetchLastModifiedAssets", AssetEditorFetchLastModifiedAssets_C2S, {
    }, 0 },
    { "AssetEditorUpdateAssetPack", AssetEditorUpdateAssetPack_BI, {
        { "id", 0x08, FType::Ptr, "String" },
        { "manifest", 0x10, FType::Ptr, "AssetPackManifest" },
    }, 2 },
    { "AssetEditorDeleteAssetPack", AssetEditorDeleteAssetPack_BI, {
        { "id", 0x08, FType::Ptr, "String" },
    }, 1 },
    { "AssetEditorSubscribeModifiedAssetsChanges", AssetEditorSubscribeModifiedAssetsChanges_C2S, {
        { "subscribe", 0x08, FType::Bool, nullptr },
    }, 1 },
    { "AssetEditorRequestDataset", AssetEditorRequestDataset_C2S, {
        { "name", 0x08, FType::Ptr, "String" },
    }, 1 },
    { "AssetEditorUndoChanges", AssetEditorUndoChanges_C2S, {
        { "path", 0x08, FType::Ptr, "AssetPath" },
        { "token", 0x10, FType::Int32, nullptr },
    }, 2 },
    { "AssetEditorSetupSchemas", AssetEditorSetupSchemas_S2C, {
    }, 0 },
    { "AssetEditorRequestDatasetReply", AssetEditorRequestDatasetReply_S2C, {
        { "name", 0x08, FType::Ptr, "String" },
    }, 1 },
    { "AssetEditorLastModifiedAssets", AssetEditorLastModifiedAssets_S2C, {
    }, 0 },
    { "AssetEditorRequestChildrenList", AssetEditorRequestChildrenList_C2S, {
        { "path", 0x08, FType::Ptr, "AssetPath" },
    }, 1 },
    { "AssetEditorCreateAsset", AssetEditorCreateAsset_C2S, {
        { "path", 0x08, FType::Ptr, "AssetPath" },
        { "data", 0x10, FType::Ptr, "Array<Byte>" },
        { "rebuild_caches", 0x18, FType::Ptr, "AssetEditorRebuildCaches" },
        { "button_id", 0x20, FType::Ptr, "String" },
        { "token", 0x28, FType::Int32, nullptr },
    }, 5 },
    { "AssetEditorUpdateAsset", AssetEditorUpdateAsset_C2S, {
        { "asset_type", 0x08, FType::Ptr, "String" },
        { "path", 0x10, FType::Ptr, "AssetPath" },
        { "data", 0x18, FType::Ptr, "Array<Byte>" },
        { "token", 0x20, FType::Int32, nullptr },
        { "asset_index", 0x24, FType::Int32, nullptr },
    }, 5 },
    { "AssetEditorCreateDirectory", AssetEditorCreateDirectory_C2S, {
        { "path", 0x08, FType::Ptr, "AssetPath" },
        { "token", 0x10, FType::Int32, nullptr },
    }, 2 },
    { "AssetEditorModifiedAssetsCount", AssetEditorModifiedAssetsCount_S2C, {
        { "count", 0x08, FType::Int32, nullptr },
    }, 1 },
    { "AssetEditorExportAssetPart", AssetEditorExportAssetPart_S2C, {
        { "part", 0x08, FType::Ptr, "Array<Byte>" },
    }, 1 },
    { "AssetEditorRedoChanges", AssetEditorRedoChanges_C2S, {
        { "path", 0x08, FType::Ptr, "AssetPath" },
        { "token", 0x10, FType::Int32, nullptr },
    }, 2 },
    { "AssetEditorDiscardChanges", AssetEditorDiscardChanges_C2S, {
    }, 0 },
    { "AssetEditorExportAssetInitialize", AssetEditorExportAssetInitialize_S2C, {
        { "asset", 0x08, FType::Ptr, "AssetEditorAsset" },
        { "old_path", 0x10, FType::Ptr, "AssetPath" },
        { "size", 0x18, FType::Int32, nullptr },
        { "failed", 0x1C, FType::Bool, nullptr },
    }, 4 },
    { "AssetEditorSetupAssetTypes", AssetEditorSetupAssetTypes_S2C, {
    }, 0 },
    { "AssetEditorFetchAssetReply", AssetEditorFetchAssetReply_S2C, {
        { "contents", 0x08, FType::Ptr, "Array<Byte>" },
        { "token", 0x10, FType::Int32, nullptr },
    }, 2 },
    { "AssetEditorUndoRedoReply", AssetEditorUndoRedoReply_S2C, {
        { "command", 0x08, FType::Ptr, "JsonUpdateCommand" },
        { "token", 0x10, FType::Int32, nullptr },
    }, 2 },
    { "AssetEditorFetchAutoCompleteDataReply", AssetEditorFetchAutoCompleteDataReply_S2C, {
        { "token", 0x08, FType::Int32, nullptr },
    }, 1 },
    { "AssetEditorModsDirectories", AssetEditorModsDirectories_S2C, {
    }, 0 },
    { "AssetEditorPopupNotification", AssetEditorPopupNotification_S2C, {
        { "message", 0x08, FType::Ptr, "FormattedMessage" },
        { "type", 0x10, FType::Int8, nullptr },
    }, 2 },
    { "AssetEditorCreateAssetPack", AssetEditorCreateAssetPack_C2S, {
        { "manifest", 0x08, FType::Ptr, "AssetPackManifest" },
        { "token", 0x10, FType::Int32, nullptr },
        { "target_directory_index", 0x14, FType::Int32, nullptr },
    }, 3 },
    { "AssetEditorAuthorization", AssetEditorAuthorization_S2C, {
        { "can_use", 0x08, FType::Bool, nullptr },
    }, 1 },
    { "AssetEditorUpdateSecondsPerGameDay", AssetEditorUpdateSecondsPerGameDay_S2C, {
        { "daytime_duration_seconds", 0x08, FType::Int32, nullptr },
        { "nighttime_duration_seconds", 0x0C, FType::Int32, nullptr },
    }, 2 },
    { "AssetEditorRequestChildrenListReply", AssetEditorRequestChildrenListReply_S2C, {
        { "path", 0x08, FType::Ptr, "AssetPath" },
    }, 1 },
    { "AssetEditorRenameAsset", AssetEditorRenameAsset_C2S, {
        { "path", 0x08, FType::Ptr, "AssetPath" },
        { "new_path", 0x10, FType::Ptr, "AssetPath" },
        { "token", 0x18, FType::Int32, nullptr },
    }, 3 },
    { "AssetEditorExportAssets", AssetEditorExportAssets_C2S, {
    }, 0 },
    { "AssetEditorFetchAutoCompleteData", AssetEditorFetchAutoCompleteData_C2S, {
        { "dataset", 0x08, FType::Ptr, "String" },
        { "query", 0x10, FType::Ptr, "String" },
        { "token", 0x18, FType::Int32, nullptr },
    }, 3 },
    { "AssetEditorAssetPackSetup", AssetEditorAssetPackSetup_S2C, {
    }, 0 },
    { "AssetEditorDeleteAsset", AssetEditorDeleteAsset_C2S, {
        { "path", 0x08, FType::Ptr, "AssetPath" },
        { "token", 0x10, FType::Int32, nullptr },
    }, 2 },
    { "AssetEditorCapabilities", AssetEditorCapabilities_S2C, {
        { "can_discard_assets", 0x08, FType::Bool, nullptr },
        { "can_edit_assets", 0x09, FType::Bool, nullptr },
        { "can_create_asset_packs", 0x0A, FType::Bool, nullptr },
        { "can_edit_asset_packs", 0x0B, FType::Bool, nullptr },
        { "can_delete_asset_packs", 0x0C, FType::Bool, nullptr },
    }, 5 },
    { "AssetEditorUpdateModelPreview", AssetEditorUpdateModelPreview_S2C, {
        { "asset_path", 0x08, FType::Ptr, "AssetPath" },
        { "model", 0x10, FType::Ptr, "Model" },
        { "block", 0x18, FType::Ptr, "BlockType" },
        { "camera", 0x20, FType::Ptr, "AssetEditorPreviewCameraSettings" },
    }, 4 },
    { "AssetEditorUpdateWeatherPreviewLock", AssetEditorUpdateWeatherPreviewLock_C2S, {
        { "locked", 0x08, FType::Bool, nullptr },
    }, 1 },
    { "AssetEditorActivateButton", AssetEditorActivateButton_C2S, {
        { "button_id", 0x08, FType::Ptr, "String" },
    }, 1 },
    { "AssetEditorExportAssetFinalize", AssetEditorExportAssetFinalize_S2C, {
    }, 0 },
    { "SetServerAccess", SetServerAccess_C2S, {
        { "password", 0x08, FType::Ptr, "String" },
        { "access", 0x10, FType::Int8, nullptr },
    }, 2 },
    { "RequestServerAccess", RequestServerAccess_S2C, {
        { "external_port", 0x08, FType::Int16, nullptr },
        { "access", 0x0A, FType::Int8, nullptr },
    }, 2 },
    { "UpdateServerAccess", UpdateServerAccess_C2S, {
        { "access", 0x08, FType::Int8, nullptr },
    }, 1 },
    { "RequestMachinimaActorModel", RequestMachinimaActorModel_C2S, {
        { "model_id", 0x08, FType::Ptr, "String" },
        { "scene_name", 0x10, FType::Ptr, "String" },
        { "actor_name", 0x18, FType::Ptr, "String" },
    }, 3 },
    { "SetMachinimaActorModel", SetMachinimaActorModel_S2C, {
        { "model", 0x08, FType::Ptr, "Model" },
        { "scene_name", 0x10, FType::Ptr, "String" },
        { "actor_name", 0x18, FType::Ptr, "String" },
    }, 3 },
    { "UpdateMachinimaScene", UpdateMachinimaScene_BI, {
        { "player", 0x08, FType::Ptr, "String" },
        { "scene_name", 0x10, FType::Ptr, "String" },
        { "scene", 0x18, FType::Ptr, "Array<Byte>" },
        { "frame", 0x20, FType::Float32, nullptr },
        { "update_type", 0x24, FType::Int8, nullptr },
    }, 5 },
    { "UpdateWorldMap", UpdateWorldMap_S2C, {
    }, 0 },
    { "UpdateWorldMapSettings", UpdateWorldMapSettings_S2C, {
        { "default_scale", 0x08, FType::Float32, nullptr },
        { "min_scale", 0x0C, FType::Float32, nullptr },
        { "max_scale", 0x10, FType::Float32, nullptr },
        { "enabled", 0x14, FType::Bool, nullptr },
        { "allow_teleport_to_coordinates", 0x15, FType::Bool, nullptr },
        { "allow_teleport_to_markers", 0x16, FType::Bool, nullptr },
        { "allow_show_on_map_toggle", 0x17, FType::Bool, nullptr },
        { "allow_compass_tracking_toggle", 0x18, FType::Bool, nullptr },
        { "allow_creating_map_markers", 0x19, FType::Bool, nullptr },
        { "allow_removing_other_players_markers", 0x1A, FType::Bool, nullptr },
    }, 10 },
    { "TeleportToWorldMapMarker", TeleportToWorldMapMarker_C2S, {
        { "id", 0x08, FType::Ptr, "String" },
    }, 1 },
    { "CreateUserMarker", CreateUserMarker_C2S, {
        { "name", 0x08, FType::Ptr, "String" },
        { "marker_image", 0x10, FType::Ptr, "String" },
        { "tint_color", 0x18, FType::Ptr, "Color" },
        { "x", 0x20, FType::Float32, nullptr },
        { "z", 0x24, FType::Float32, nullptr },
        { "shared", 0x28, FType::Bool, nullptr },
    }, 6 },
    { "ClearWorldMap", ClearWorldMap_S2C, {
    }, 0 },
    { "TeleportToWorldMapPosition", TeleportToWorldMapPosition_C2S, {
        { "x", 0x08, FType::Int32, nullptr },
        { "y", 0x0C, FType::Int32, nullptr },
    }, 2 },
    { "UpdateWorldMapVisible", UpdateWorldMapVisible_C2S, {
        { "visible", 0x08, FType::Bool, nullptr },
    }, 1 },
    { "StreamOpen", StreamOpen_C2S, {
        { "type", 0x08, FType::Int8, nullptr },
    }, 1 },
    { "StreamOpenResponse", StreamOpenResponse_S2C, {
        { "rejection_reason", 0x08, FType::Ptr, "String" },
        { "type", 0x10, FType::Int8, nullptr },
        { "accepted", 0x11, FType::Bool, nullptr },
    }, 3 },
    { "ServerAuthToken", ServerAuthToken_S2C, {
        { "server_access_token", 0x08, FType::Ptr, "String" },
        { "password_challenge", 0x10, FType::Ptr, "Array<Byte>" },
    }, 2 },
    { "PasswordAccepted", PasswordAccepted_S2C, {
    }, 0 },
    { "ConnectAccept", ConnectAccept_S2C, {
        { "password_challenge", 0x08, FType::Ptr, "Array<Byte>" },
    }, 1 },
    { "AuthGrant", AuthGrant_S2C, {
        { "authorization_grant", 0x08, FType::Ptr, "String" },
        { "server_identity_token", 0x10, FType::Ptr, "String" },
    }, 2 },
    { "AuthToken", AuthToken_C2S, {
        { "access_token", 0x08, FType::Ptr, "String" },
        { "server_authorization_grant", 0x10, FType::Ptr, "String" },
    }, 2 },
    { "ClientReferral", ClientReferral_S2C, {
        { "host_to", 0x08, FType::Ptr, "HostAddress" },
        { "data", 0x10, FType::Ptr, "Array<Byte>" },
    }, 2 },
    { "PasswordRejected", PasswordRejected_S2C, {
        { "new_challenge", 0x08, FType::Ptr, "Array<Byte>" },
        { "attempts_remaining", 0x10, FType::Int32, nullptr },
    }, 2 },
    { "PasswordResponse", PasswordResponse_C2S, {
        { "hash", 0x08, FType::Ptr, "Array<Byte>" },
    }, 1 },
};
inline constexpr int PKT_TABLE_SIZE = 279;

// ── Sub-type table ───────────────────────────────────────────────────
struct SubTypeDef {
    const char* name;
    FieldDesc   fields[128];
    int         field_count;
};

inline const SubTypeDef SUB_TYPE_TABLE[] = {
    { "Asset", {
        { "hash", 0x08, FType::Ptr, "String" },
        { "name", 0x10, FType::Ptr, "String" },
    }, 2 },
    { "AssetEditorAsset", {
        { "hash", 0x08, FType::Ptr, "String" },
        { "path", 0x10, FType::Ptr, "AssetPath" },
    }, 2 },
    { "AssetEditorPreviewCameraSettings", {
        { "camera_position", 0x08, FType::Ptr, "Vector3f" },
        { "camera_orientation", 0x10, FType::Ptr, "Vector3f" },
        { "model_scale", 0x18, FType::Float32, nullptr },
    }, 3 },
    { "AssetEditorRebuildCaches", {
        { "block_textures", 0x08, FType::Bool, nullptr },
        { "models", 0x09, FType::Bool, nullptr },
        { "model_textures", 0x0A, FType::Bool, nullptr },
        { "map_geometry", 0x0B, FType::Bool, nullptr },
        { "item_icons", 0x0C, FType::Bool, nullptr },
    }, 5 },
    { "AssetPackManifest", {
        { "name", 0x08, FType::Ptr, "String" },
        { "group", 0x10, FType::Ptr, "String" },
        { "website", 0x18, FType::Ptr, "String" },
        { "description", 0x20, FType::Ptr, "String" },
        { "version", 0x28, FType::Ptr, "String" },
        { "server_version", 0x30, FType::Ptr, "String" },
    }, 6 },
    { "AssetPath", {
        { "pack", 0x08, FType::Ptr, "String" },
        { "path", 0x10, FType::Ptr, "String" },
    }, 2 },
    { "Bench", {
    }, 0 },
    { "BlockBreaking", {
        { "gather_type", 0x08, FType::Ptr, "String" },
        { "item_id", 0x10, FType::Ptr, "String" },
        { "drop_list_id", 0x18, FType::Ptr, "String" },
        { "health", 0x20, FType::Float32, nullptr },
        { "quantity", 0x24, FType::Int32, nullptr },
        { "quality", 0x28, FType::Int32, nullptr },
    }, 6 },
    { "BlockFlags", {
        { "is_usable", 0x08, FType::Bool, nullptr },
        { "is_stackable", 0x09, FType::Bool, nullptr },
    }, 2 },
    { "BlockGathering", {
        { "breaking", 0x08, FType::Ptr, "BlockBreaking" },
        { "harvest", 0x10, FType::Ptr, "Harvesting" },
        { "soft", 0x18, FType::Ptr, "SoftBlock" },
    }, 3 },
    { "BlockMovementSettings", {
        { "climb_up_speed_multiplier", 0x08, FType::Float32, nullptr },
        { "climb_down_speed_multiplier", 0x0C, FType::Float32, nullptr },
        { "climb_lateral_speed_multiplier", 0x10, FType::Float32, nullptr },
        { "bounce_velocity", 0x14, FType::Float32, nullptr },
        { "drag", 0x18, FType::Float32, nullptr },
        { "friction", 0x1C, FType::Float32, nullptr },
        { "terminal_velocity_modifier", 0x20, FType::Float32, nullptr },
        { "horizontal_speed_multiplier", 0x24, FType::Float32, nullptr },
        { "acceleration", 0x28, FType::Float32, nullptr },
        { "jump_force_multiplier", 0x2C, FType::Float32, nullptr },
        { "is_climbable", 0x30, FType::Bool, nullptr },
        { "is_bouncy", 0x31, FType::Bool, nullptr },
    }, 12 },
    { "BlockPlacementSettings", {
        { "wall_placement_override_block_id", 0x08, FType::Int32, nullptr },
        { "floor_placement_override_block_id", 0x0C, FType::Int32, nullptr },
        { "ceiling_placement_override_block_id", 0x10, FType::Int32, nullptr },
        { "allow_rotation_key", 0x14, FType::Bool, nullptr },
        { "place_in_empty_blocks", 0x15, FType::Bool, nullptr },
        { "preview_visibility", 0x16, FType::Int8, nullptr },
        { "rotation_mode", 0x17, FType::Int8, nullptr },
        { "allow_break_replace", 0x18, FType::Bool, nullptr },
    }, 8 },
    { "BlockPosition", {
        { "x", 0x08, FType::Int32, nullptr },
        { "y", 0x0C, FType::Int32, nullptr },
        { "z", 0x10, FType::Int32, nullptr },
    }, 3 },
    { "BlockRotation", {
        { "rotation_yaw", 0x08, FType::Int8, nullptr },
        { "rotation_pitch", 0x09, FType::Int8, nullptr },
        { "rotation_roll", 0x0A, FType::Int8, nullptr },
    }, 3 },
    { "BlockType", {
        { "item", 0x08, FType::Ptr, "String" },
        { "name", 0x10, FType::Ptr, "String" },
        { "shader_effect", 0x18, FType::Ptr, "Array<ShaderType>" },
        { "model", 0x20, FType::Ptr, "String" },
        { "model_animation", 0x28, FType::Ptr, "String" },
        { "cube_side_mask_texture", 0x30, FType::Ptr, "String" },
        { "block_particle_set_id", 0x38, FType::Ptr, "String" },
        { "block_breaking_decal_id", 0x40, FType::Ptr, "String" },
        { "particle_color", 0x48, FType::Ptr, "Color" },
        { "light", 0x50, FType::Ptr, "ColorLight" },
        { "tint", 0x58, FType::Ptr, "Tint" },
        { "biome_tint", 0x60, FType::Ptr, "Tint" },
        { "transition_texture", 0x68, FType::Ptr, "String" },
        { "transition_to_groups", 0x70, FType::Ptr, "Array<int>" },
        { "movement_settings", 0x78, FType::Ptr, "BlockMovementSettings" },
        { "flags", 0x80, FType::Ptr, "BlockFlags" },
        { "interaction_hint", 0x88, FType::Ptr, "String" },
        { "gathering", 0x90, FType::Ptr, "BlockGathering" },
        { "placement_settings", 0x98, FType::Ptr, "BlockPlacementSettings" },
        { "display", 0xA0, FType::Ptr, "ModelDisplay" },
        { "rail", 0xA8, FType::Ptr, "RailConfig" },
        { "tag_indexes", 0xB0, FType::Ptr, "Array<int>" },
        { "bench", 0xB8, FType::Ptr, "Bench" },
        { "connected_block_rule_set", 0xC0, FType::Ptr, "ConnectedBlockRuleSet" },
        { "hitbox", 0xC8, FType::Int32, nullptr },
        { "interaction_hitbox", 0xCC, FType::Int32, nullptr },
        { "model_scale", 0xD0, FType::Float32, nullptr },
        { "max_support_distance", 0xD4, FType::Int32, nullptr },
        { "block_sound_set_index", 0xD8, FType::Int32, nullptr },
        { "ambient_sound_event_index", 0xDC, FType::Int32, nullptr },
        { "group", 0xE0, FType::Int32, nullptr },
        { "transition_to_tag", 0xE4, FType::Int32, nullptr },
        { "unknown", 0xE8, FType::Bool, nullptr },
        { "draw_type", 0xE9, FType::Int8, nullptr },
        { "material", 0xEA, FType::Int8, nullptr },
        { "opacity", 0xEB, FType::Int8, nullptr },
        { "looping", 0xEC, FType::Bool, nullptr },
        { "block_supports_required_for", 0xED, FType::Int8, nullptr },
        { "requires_alpha_blending", 0xEE, FType::Bool, nullptr },
        { "cube_shading_mode", 0xEF, FType::Int8, nullptr },
        { "random_rotation", 0xF0, FType::Int8, nullptr },
        { "variant_rotation", 0xF1, FType::Int8, nullptr },
        { "rotation_yaw_placement_offset", 0xF2, FType::Int8, nullptr },
        { "ignore_support_when_placed", 0xF3, FType::Bool, nullptr },
    }, 44 },
    { "CameraAxis", {
        { "angle_range", 0x08, FType::Ptr, "Rangef" },
        { "target_nodes", 0x10, FType::Ptr, "Array<CameraNode>" },
    }, 2 },
    { "CameraSettings", {
        { "position_offset", 0x08, FType::Ptr, "Vector3f" },
        { "yaw", 0x10, FType::Ptr, "CameraAxis" },
        { "pitch", 0x18, FType::Ptr, "CameraAxis" },
    }, 3 },
    { "Color", {
        { "red", 0x08, FType::Int8, nullptr },
        { "green", 0x09, FType::Int8, nullptr },
        { "blue", 0x0A, FType::Int8, nullptr },
    }, 3 },
    { "ColorLight", {
        { "radius", 0x08, FType::Int8, nullptr },
        { "red", 0x09, FType::Int8, nullptr },
        { "green", 0x0A, FType::Int8, nullptr },
        { "blue", 0x0B, FType::Int8, nullptr },
    }, 4 },
    { "ConnectedBlockRuleSet", {
        { "stair", 0x08, FType::Ptr, "StairConnectedBlockRuleSet" },
        { "roof", 0x10, FType::Ptr, "RoofConnectedBlockRuleSet" },
        { "type", 0x18, FType::Int8, nullptr },
    }, 3 },
    { "DamageCause", {
        { "id", 0x08, FType::Ptr, "String" },
        { "damage_text_color", 0x10, FType::Ptr, "String" },
    }, 2 },
    { "Direction", {
        { "yaw", 0x08, FType::Float32, nullptr },
        { "pitch", 0x0C, FType::Float32, nullptr },
        { "roll", 0x10, FType::Float32, nullptr },
    }, 3 },
    { "EditorSelection", {
        { "min_x", 0x08, FType::Int32, nullptr },
        { "min_y", 0x0C, FType::Int32, nullptr },
        { "min_z", 0x10, FType::Int32, nullptr },
        { "max_x", 0x14, FType::Int32, nullptr },
        { "max_y", 0x18, FType::Int32, nullptr },
        { "max_z", 0x1C, FType::Int32, nullptr },
    }, 6 },
    { "ExtraResources", {
    }, 0 },
    { "ForkedChainId", {
        { "forked_id", 0x08, FType::Ptr, "ForkedChainId" },
        { "entry_index", 0x10, FType::Int32, nullptr },
        { "sub_index", 0x14, FType::Int32, nullptr },
    }, 3 },
    { "FormattedMessage", {
        { "raw_text", 0x08, FType::Ptr, "String" },
        { "message_id", 0x10, FType::Ptr, "String" },
        { "color", 0x18, FType::Ptr, "String" },
        { "link", 0x20, FType::Ptr, "String" },
        { "image", 0x28, FType::Ptr, "FormattedMessageImage" },
        { "bold", 0x30, FType::Int8, nullptr },
        { "italic", 0x31, FType::Int8, nullptr },
        { "monospace", 0x32, FType::Int8, nullptr },
        { "underlined", 0x33, FType::Int8, nullptr },
        { "markup_enabled", 0x34, FType::Bool, nullptr },
    }, 10 },
    { "FormattedMessageImage", {
        { "file_path", 0x08, FType::Ptr, "String" },
        { "width", 0x10, FType::Int32, nullptr },
        { "height", 0x14, FType::Int32, nullptr },
    }, 3 },
    { "Guuid", {
        { "a", 0x08, FType::Int32, nullptr },
        { "b", 0x0C, FType::Int16, nullptr },
        { "c", 0x0E, FType::Int16, nullptr },
    }, 3 },
    { "HalfFloatPosition", {
        { "x", 0x08, FType::Int16, nullptr },
        { "y", 0x0A, FType::Int16, nullptr },
        { "z", 0x0C, FType::Int16, nullptr },
    }, 3 },
    { "Harvesting", {
        { "item_id", 0x08, FType::Ptr, "String" },
        { "drop_list_id", 0x10, FType::Ptr, "String" },
    }, 2 },
    { "Hitbox", {
        { "min_x", 0x08, FType::Float32, nullptr },
        { "min_y", 0x0C, FType::Float32, nullptr },
        { "min_z", 0x10, FType::Float32, nullptr },
        { "max_x", 0x14, FType::Float32, nullptr },
        { "max_y", 0x18, FType::Float32, nullptr },
        { "max_z", 0x1C, FType::Float32, nullptr },
    }, 6 },
    { "HostAddress", {
        { "host", 0x08, FType::Ptr, "String" },
        { "port", 0x10, FType::Int16, nullptr },
    }, 2 },
    { "InstantData", {
        { "seconds", 0x08, FType::Int64, nullptr },
        { "nanos", 0x10, FType::Int32, nullptr },
    }, 2 },
    { "InventorySection", {
        { "capacity", 0x08, FType::Int16, nullptr },
    }, 1 },
    { "ItemQuantity", {
        { "item_id", 0x08, FType::Ptr, "String" },
        { "quantity", 0x10, FType::Int32, nullptr },
    }, 2 },
    { "ItemWithAllMetadata", {
        { "item_id", 0x08, FType::Ptr, "String" },
        { "metadata", 0x10, FType::Ptr, "String" },
        { "durability", 0x18, FType::Float64, nullptr },
        { "max_durability", 0x20, FType::Float64, nullptr },
        { "quantity", 0x28, FType::Int32, nullptr },
        { "override_dropped_item_animation", 0x2C, FType::Bool, nullptr },
    }, 6 },
    { "JsonUpdateCommand", {
        { "value", 0x08, FType::Ptr, "String" },
        { "previous_value", 0x10, FType::Ptr, "String" },
        { "rebuild_caches", 0x18, FType::Ptr, "AssetEditorRebuildCaches" },
        { "type", 0x20, FType::Int8, nullptr },
    }, 4 },
    { "Model", {
        { "asset_id", 0x08, FType::Ptr, "String" },
        { "path", 0x10, FType::Ptr, "String" },
        { "texture", 0x18, FType::Ptr, "String" },
        { "gradient_set", 0x20, FType::Ptr, "String" },
        { "gradient_id", 0x28, FType::Ptr, "String" },
        { "camera", 0x30, FType::Ptr, "CameraSettings" },
        { "hitbox", 0x38, FType::Ptr, "Hitbox" },
        { "light", 0x40, FType::Ptr, "ColorLight" },
        { "phobia_model", 0x48, FType::Ptr, "Model" },
        { "scale", 0x50, FType::Float32, nullptr },
        { "eye_height", 0x54, FType::Float32, nullptr },
        { "crouch_offset", 0x58, FType::Float32, nullptr },
        { "sitting_offset", 0x5C, FType::Float32, nullptr },
        { "sleeping_offset", 0x60, FType::Float32, nullptr },
        { "phobia", 0x64, FType::Int8, nullptr },
    }, 15 },
    { "ModelDisplay", {
        { "node", 0x08, FType::Ptr, "String" },
        { "attach_to", 0x10, FType::Ptr, "String" },
        { "translation", 0x18, FType::Ptr, "Vector3f" },
        { "rotation", 0x20, FType::Ptr, "Vector3f" },
        { "scale", 0x28, FType::Ptr, "Vector3f" },
    }, 5 },
    { "ModelTransform", {
        { "position", 0x08, FType::Ptr, "Position" },
        { "body_orientation", 0x10, FType::Ptr, "Direction" },
        { "look_orientation", 0x18, FType::Ptr, "Direction" },
    }, 3 },
    { "MouseButtonEvent", {
        { "mouse_button_type", 0x08, FType::Int8, nullptr },
        { "state", 0x09, FType::Int8, nullptr },
        { "clicks", 0x0A, FType::Int8, nullptr },
    }, 3 },
    { "MouseMotionEvent", {
        { "mouse_button_type", 0x08, FType::Ptr, "Array<MouseButtonType>" },
        { "relative_motion", 0x10, FType::Ptr, "Vector2i" },
    }, 2 },
    { "MovementSettings", {
        { "mass", 0x08, FType::Float32, nullptr },
        { "drag_coefficient", 0x0C, FType::Float32, nullptr },
        { "velocity_resistance", 0x10, FType::Float32, nullptr },
        { "jump_force", 0x14, FType::Float32, nullptr },
        { "swim_jump_force", 0x18, FType::Float32, nullptr },
        { "jump_buffer_duration", 0x1C, FType::Float32, nullptr },
        { "jump_buffer_max_y_velocity", 0x20, FType::Float32, nullptr },
        { "acceleration", 0x24, FType::Float32, nullptr },
        { "air_drag_min", 0x28, FType::Float32, nullptr },
        { "air_drag_max", 0x2C, FType::Float32, nullptr },
        { "air_drag_min_speed", 0x30, FType::Float32, nullptr },
        { "air_drag_max_speed", 0x34, FType::Float32, nullptr },
        { "air_friction_min", 0x38, FType::Float32, nullptr },
        { "air_friction_max", 0x3C, FType::Float32, nullptr },
        { "air_friction_min_speed", 0x40, FType::Float32, nullptr },
        { "air_friction_max_speed", 0x44, FType::Float32, nullptr },
        { "air_speed_multiplier", 0x48, FType::Float32, nullptr },
        { "air_control_min_speed", 0x4C, FType::Float32, nullptr },
        { "air_control_max_speed", 0x50, FType::Float32, nullptr },
        { "air_control_min_multiplier", 0x54, FType::Float32, nullptr },
        { "air_control_max_multiplier", 0x58, FType::Float32, nullptr },
        { "combo_air_speed_multiplier", 0x5C, FType::Float32, nullptr },
        { "base_speed", 0x60, FType::Float32, nullptr },
        { "climb_speed", 0x64, FType::Float32, nullptr },
        { "climb_speed_lateral", 0x68, FType::Float32, nullptr },
        { "climb_up_sprint_speed", 0x6C, FType::Float32, nullptr },
        { "climb_down_sprint_speed", 0x70, FType::Float32, nullptr },
        { "horizontal_fly_speed", 0x74, FType::Float32, nullptr },
        { "vertical_fly_speed", 0x78, FType::Float32, nullptr },
        { "max_speed_multiplier", 0x7C, FType::Float32, nullptr },
        { "min_speed_multiplier", 0x80, FType::Float32, nullptr },
        { "wish_direction_gravity_x", 0x84, FType::Float32, nullptr },
        { "wish_direction_gravity_y", 0x88, FType::Float32, nullptr },
        { "wish_direction_weight_x", 0x8C, FType::Float32, nullptr },
        { "wish_direction_weight_y", 0x90, FType::Float32, nullptr },
        { "collision_expulsion_force", 0x94, FType::Float32, nullptr },
        { "forward_walk_speed_multiplier", 0x98, FType::Float32, nullptr },
        { "backward_walk_speed_multiplier", 0x9C, FType::Float32, nullptr },
        { "strafe_walk_speed_multiplier", 0xA0, FType::Float32, nullptr },
        { "forward_run_speed_multiplier", 0xA4, FType::Float32, nullptr },
        { "backward_run_speed_multiplier", 0xA8, FType::Float32, nullptr },
        { "strafe_run_speed_multiplier", 0xAC, FType::Float32, nullptr },
        { "forward_crouch_speed_multiplier", 0xB0, FType::Float32, nullptr },
        { "backward_crouch_speed_multiplier", 0xB4, FType::Float32, nullptr },
        { "strafe_crouch_speed_multiplier", 0xB8, FType::Float32, nullptr },
        { "forward_sprint_speed_multiplier", 0xBC, FType::Float32, nullptr },
        { "variable_jump_fall_force", 0xC0, FType::Float32, nullptr },
        { "fall_effect_duration", 0xC4, FType::Float32, nullptr },
        { "fall_jump_force", 0xC8, FType::Float32, nullptr },
        { "fall_momentum_loss", 0xCC, FType::Float32, nullptr },
        { "auto_jump_obstacle_speed_loss", 0xD0, FType::Float32, nullptr },
        { "auto_jump_obstacle_sprint_speed_loss", 0xD4, FType::Float32, nullptr },
        { "auto_jump_obstacle_effect_duration", 0xD8, FType::Float32, nullptr },
        { "auto_jump_obstacle_sprint_effect_duration", 0xDC, FType::Float32, nullptr },
        { "auto_jump_obstacle_max_angle", 0xE0, FType::Float32, nullptr },
        { "min_slide_entry_speed", 0xE4, FType::Float32, nullptr },
        { "slide_exit_speed", 0xE8, FType::Float32, nullptr },
        { "min_fall_speed_to_engage_roll", 0xEC, FType::Float32, nullptr },
        { "max_fall_speed_to_engage_roll", 0xF0, FType::Float32, nullptr },
        { "roll_start_speed_modifier", 0xF4, FType::Float32, nullptr },
        { "roll_exit_speed_modifier", 0xF8, FType::Float32, nullptr },
        { "roll_time_to_complete", 0xFC, FType::Float32, nullptr },
        { "inverted_gravity", 0x100, FType::Bool, nullptr },
        { "can_fly", 0x101, FType::Bool, nullptr },
        { "auto_jump_disable_jumping", 0x102, FType::Bool, nullptr },
    }, 65 },
    { "MovementStates", {
        { "idle", 0x08, FType::Bool, nullptr },
        { "horizontal_idle", 0x09, FType::Bool, nullptr },
        { "jumping", 0x0A, FType::Bool, nullptr },
        { "flying", 0x0B, FType::Bool, nullptr },
        { "walking", 0x0C, FType::Bool, nullptr },
        { "running", 0x0D, FType::Bool, nullptr },
        { "sprinting", 0x0E, FType::Bool, nullptr },
        { "crouching", 0x0F, FType::Bool, nullptr },
        { "forced_crouching", 0x10, FType::Bool, nullptr },
        { "falling", 0x11, FType::Bool, nullptr },
        { "falling_far", 0x12, FType::Bool, nullptr },
        { "climbing", 0x13, FType::Bool, nullptr },
        { "in_fluid", 0x14, FType::Bool, nullptr },
        { "swimming", 0x15, FType::Bool, nullptr },
        { "swim_jumping", 0x16, FType::Bool, nullptr },
        { "on_ground", 0x17, FType::Bool, nullptr },
        { "mantling", 0x18, FType::Bool, nullptr },
        { "sliding", 0x19, FType::Bool, nullptr },
        { "mounting", 0x1A, FType::Bool, nullptr },
        { "rolling", 0x1B, FType::Bool, nullptr },
        { "sitting", 0x1C, FType::Bool, nullptr },
        { "gliding", 0x1D, FType::Bool, nullptr },
        { "sleeping", 0x1E, FType::Bool, nullptr },
    }, 23 },
    { "Objective", {
        { "objective_title_key", 0x08, FType::Ptr, "FormattedMessage" },
        { "objective_description_key", 0x10, FType::Ptr, "FormattedMessage" },
        { "objective_line_id", 0x18, FType::Ptr, "String" },
        { "objective_uuid", 0x20, FType::Ptr, "Guuid" },
    }, 4 },
    { "ObjectiveTask", {
        { "task_description_key", 0x08, FType::Ptr, "FormattedMessage" },
        { "current_completion", 0x10, FType::Int32, nullptr },
        { "completion_needed", 0x14, FType::Int32, nullptr },
    }, 3 },
    { "PlayerSkin", {
        { "body_characteristic", 0x08, FType::Ptr, "String" },
        { "underwear", 0x10, FType::Ptr, "String" },
        { "face", 0x18, FType::Ptr, "String" },
        { "eyes", 0x20, FType::Ptr, "String" },
        { "ears", 0x28, FType::Ptr, "String" },
        { "mouth", 0x30, FType::Ptr, "String" },
        { "facial_hair", 0x38, FType::Ptr, "String" },
        { "haircut", 0x40, FType::Ptr, "String" },
        { "eyebrows", 0x48, FType::Ptr, "String" },
        { "pants", 0x50, FType::Ptr, "String" },
        { "overpants", 0x58, FType::Ptr, "String" },
        { "undertop", 0x60, FType::Ptr, "String" },
        { "overtop", 0x68, FType::Ptr, "String" },
        { "shoes", 0x70, FType::Ptr, "String" },
        { "head_accessory", 0x78, FType::Ptr, "String" },
        { "face_accessory", 0x80, FType::Ptr, "String" },
        { "ear_accessory", 0x88, FType::Ptr, "String" },
        { "skin_feature", 0x90, FType::Ptr, "String" },
        { "gloves", 0x98, FType::Ptr, "String" },
        { "cape", 0xA0, FType::Ptr, "String" },
    }, 20 },
    { "PortalDef", {
        { "name_key", 0x08, FType::Ptr, "String" },
        { "exploration_seconds", 0x10, FType::Int32, nullptr },
        { "breach_seconds", 0x14, FType::Int32, nullptr },
    }, 3 },
    { "PortalState", {
        { "remaining_seconds", 0x08, FType::Int32, nullptr },
        { "breaching", 0x0C, FType::Bool, nullptr },
    }, 2 },
    { "Position", {
        { "x", 0x08, FType::Float64, nullptr },
        { "y", 0x10, FType::Float64, nullptr },
        { "z", 0x18, FType::Float64, nullptr },
    }, 3 },
    { "Quaternionfc", {
    }, 0 },
    { "RailConfig", {
    }, 0 },
    { "Rangef", {
        { "min", 0x08, FType::Float32, nullptr },
        { "max", 0x0C, FType::Float32, nullptr },
    }, 2 },
    { "RoofConnectedBlockRuleSet", {
        { "regular", 0x08, FType::Ptr, "StairConnectedBlockRuleSet" },
        { "hollow", 0x10, FType::Ptr, "StairConnectedBlockRuleSet" },
        { "material_name", 0x18, FType::Ptr, "String" },
        { "topper_block_id", 0x20, FType::Int32, nullptr },
        { "width", 0x24, FType::Int32, nullptr },
    }, 5 },
    { "SavedMovementStates", {
        { "flying", 0x08, FType::Bool, nullptr },
    }, 1 },
    { "ServerCameraSettings", {
        { "movement_force_rotation", 0x08, FType::Ptr, "Direction" },
        { "position_offset", 0x10, FType::Ptr, "Position" },
        { "rotation_offset", 0x18, FType::Ptr, "Direction" },
        { "position", 0x20, FType::Ptr, "Position" },
        { "rotation", 0x28, FType::Ptr, "Direction" },
        { "movement_multiplier", 0x30, FType::Ptr, "Vector3f" },
        { "look_multiplier", 0x38, FType::Ptr, "Vector2f" },
        { "plane_normal", 0x40, FType::Ptr, "Vector3f" },
        { "position_lerp_speed", 0x48, FType::Float32, nullptr },
        { "rotation_lerp_speed", 0x4C, FType::Float32, nullptr },
        { "distance", 0x50, FType::Float32, nullptr },
        { "speed_modifier", 0x54, FType::Float32, nullptr },
        { "attached_to_entity_id", 0x58, FType::Int32, nullptr },
        { "allow_pitch_controls", 0x5C, FType::Bool, nullptr },
        { "display_cursor", 0x5D, FType::Bool, nullptr },
        { "display_reticle", 0x5E, FType::Bool, nullptr },
        { "mouse_input_target_type", 0x5F, FType::Int8, nullptr },
        { "send_mouse_motion", 0x60, FType::Bool, nullptr },
        { "skip_character_physics", 0x61, FType::Bool, nullptr },
        { "is_first_person", 0x62, FType::Bool, nullptr },
        { "movement_force_rotation_type", 0x63, FType::Int8, nullptr },
        { "attached_to_type", 0x64, FType::Int8, nullptr },
        { "eye_offset", 0x65, FType::Bool, nullptr },
        { "position_distance_offset_type", 0x66, FType::Int8, nullptr },
        { "position_type", 0x67, FType::Int8, nullptr },
        { "rotation_type", 0x68, FType::Int8, nullptr },
        { "can_move_type", 0x69, FType::Int8, nullptr },
        { "apply_movement_type", 0x6A, FType::Int8, nullptr },
        { "apply_look_type", 0x6B, FType::Int8, nullptr },
        { "mouse_input_type", 0x6C, FType::Int8, nullptr },
    }, 30 },
    { "SleepClock", {
        { "start_gametime", 0x08, FType::Ptr, "InstantData" },
        { "target_gametime", 0x10, FType::Ptr, "InstantData" },
        { "progress", 0x18, FType::Float32, nullptr },
        { "duration_seconds", 0x1C, FType::Float32, nullptr },
    }, 4 },
    { "SleepMultiplayer", {
        { "awake_sample", 0x08, FType::Ptr, "Array<Guuid>" },
        { "sleepers_count", 0x10, FType::Int32, nullptr },
        { "awake_count", 0x14, FType::Int32, nullptr },
    }, 3 },
    { "SoftBlock", {
        { "item_id", 0x08, FType::Ptr, "String" },
        { "drop_list_id", 0x10, FType::Ptr, "String" },
        { "is_weapon_breakable", 0x18, FType::Bool, nullptr },
    }, 3 },
    { "StairConnectedBlockRuleSet", {
        { "material_name", 0x08, FType::Ptr, "String" },
        { "straight_block_id", 0x10, FType::Int32, nullptr },
        { "corner_left_block_id", 0x14, FType::Int32, nullptr },
        { "corner_right_block_id", 0x18, FType::Int32, nullptr },
        { "inverted_corner_left_block_id", 0x1C, FType::Int32, nullptr },
        { "inverted_corner_right_block_id", 0x20, FType::Int32, nullptr },
    }, 6 },
    { "String", {
    }, 0 },
    { "TeleportAck", {
        { "teleport_id", 0x08, FType::Int8, nullptr },
    }, 1 },
    { "Tint", {
        { "top", 0x08, FType::Int32, nullptr },
        { "bottom", 0x0C, FType::Int32, nullptr },
        { "front", 0x10, FType::Int32, nullptr },
        { "back", 0x14, FType::Int32, nullptr },
        { "left", 0x18, FType::Int32, nullptr },
        { "right", 0x1C, FType::Int32, nullptr },
    }, 6 },
    { "Vector2f", {
        { "x", 0x08, FType::Float32, nullptr },
        { "y", 0x0C, FType::Float32, nullptr },
    }, 2 },
    { "Vector2i", {
        { "x", 0x08, FType::Int32, nullptr },
        { "y", 0x0C, FType::Int32, nullptr },
    }, 2 },
    { "Vector3d", {
        { "x", 0x08, FType::Float64, nullptr },
        { "y", 0x10, FType::Float64, nullptr },
        { "z", 0x18, FType::Float64, nullptr },
    }, 3 },
    { "Vector3f", {
        { "x", 0x08, FType::Float32, nullptr },
        { "y", 0x0C, FType::Float32, nullptr },
        { "z", 0x10, FType::Float32, nullptr },
    }, 3 },
    { "VelocityConfig", {
        { "ground_resistance", 0x08, FType::Float32, nullptr },
        { "ground_resistance_max", 0x0C, FType::Float32, nullptr },
        { "air_resistance", 0x10, FType::Float32, nullptr },
        { "air_resistance_max", 0x14, FType::Float32, nullptr },
        { "threshold", 0x18, FType::Float32, nullptr },
        { "style", 0x1C, FType::Int8, nullptr },
    }, 6 },
    { "WindowAction", {
    }, 0 },
    { "WorldInteraction", {
        { "block_position", 0x08, FType::Ptr, "BlockPosition" },
        { "block_rotation", 0x10, FType::Ptr, "BlockRotation" },
        { "entity_id", 0x18, FType::Int32, nullptr },
    }, 3 },
};
inline constexpr int SUB_TYPE_TABLE_SIZE = 70;

}  // namespace PacketTable
